### PR TITLE
Rebuild cortex-m newlib libraries

### PR DESCRIPTION
**Pull request by bradjc**
I rebuilt the newlib libraries for cortex-m, and added them based on thumb versions.

However, cortex-m4 with v7e-m doesn't work for me. I get faults for many apps in the reldata fixup section. Using v7-m for cortex-m4 seems to work.

### CODE REVIEW

**Comment by bradjc** [comment]
Oh. This looks bad:

```
❯ tockloader inspect-tab --crt0-header
[INFO   ] No TABs passed to tockloader.
[STATUS ] Searching for TABs in subdirectories.
[INFO   ] Using: ['./build/adc_continuous.tab']
[STATUS ] Inspecting TABs...
TAB: adc_continuous
  build-date: 2021-08-20 15:50:18+00:00
  minimum-tock-kernel-version: 2.0
  only-for-boards:
  tab-version: 1
  included architectures: cortex-m0, cortex-m3, cortex-m4, cortex-m7

Which TBF to inspect further?
[0]	cortex-m0
[1]	cortex-m3
[2]	cortex-m4
[3]	cortex-m7
[4]	None

Which option? [0] 2

cortex-m4:
  version               : 2
  header_size           :         60         0x3c
  total_size            :       8192       0x2000
  checksum              :              0x44420304
  flags                 :          1          0x1
    enabled             : Yes
    sticky              : No
  TLV: Main (1)
    init_fn_offset      :         41         0x29
    protected_size      :          0          0x0
    minimum_ram_size    :      13624       0x3538
  TLV: Package Name (3)
    package_name        : adc_continuous
  TLV: Kernel Version (8)
    kernel_major        : 2
    kernel_minor        : 0
    kernel version      : ^2.0

  crt0 header
    got_sym_start       :       7104       0x1bc0
    got_start           :       2048        0x800
    got_size            :        224         0xe0
    data_sym_start      :       7328       0x1ca0
    data_start          :       2272        0x8e0
    data_size           :        112         0x70
    bss_start           :       2384        0x950
    bss_size            :       9192       0x23e8
    reldata_start       :       7440       0x1d10
      [reldata_len]     :      88322      0x15902
    stack_size          :       2048        0x800
```
88322 bytes???

**Comment by bradjc** [comment]
The .tbf file was not created the same as the .elf file. https://github.com/tock/elf2tab/pull/35 in elf2tab addresses the issue.

**Review by hudson-ayers — APPROVED** [review]
Tested blink + adc + udp_send on nano33ble and seems to work well!

**Comment by hudson-ayers** [comment]
Merging bc this is clearly better than the current, broken newlib. But additional testing from anyone is appreciated.

bors r+

**Pull request merged**
