### PR TITLE
Tock 2.0 switchover

### PR DESCRIPTION
**Pull request by phil-levis**
This PR 
1. removes the Tock 1.0 system calls from tock.c,
2. changes `subscribe_cb` to `subscribe_upcall`
3. updates `driver_exists` to use `command2`

It **does not** yet change the names (e.g., `command2` to `command`). This because many userspace libraries have not been ported to the new system calls:

- [x] tsl2561 @ppannuto #182
- [x] temperature @phil-levis #178 
- [x] ~aes~ 
- [x] ~st7735~ #185 
- [x] pca9544a @alevy 
- [x] lsm303dlhc #191 @alexandruradovici 
- [x] usb @alistair23 #189 
- [x] ~console~ (minor, fixed in this PR) @phil-levis #177 
- [x] proximity @alevy  #181
- [x] ltc294x @alevy #180 
- [x] ~tmp006~ #184 
- [x] l3gd20 #192 @alexandruradovici 
- [x] lps35hb #187 
- [x] humidity @phil-levis #178 
- [x] max17205 #183 
- [x] ipc @alevy #176, #177

This causes an undefined symbol when compiling, so libtock-c is not usable/linkable. But it does compile. As these are fixed, tested, and pushed to `tock-2.0-dev`, I will keep this branch up to date and unblock it when it is ready.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
IPC changes were merged before this PR (https://github.com/tock/libtock-c/pull/176)

**Comment by hudson-ayers** [comment]
The in-kernel AES driver was removed 3 years ago (https://github.com/tock/tock/pull/684) and never brought back. At the time the removal was intended to be temporary, but it was never brought back, and I am guessing it would be a decent amount of work to bring it back and test it now. Should we block tock 2.0 on this, or just removed the userspace driver from `libtock-c` (and actually create an issue tracking that we want to bring it back)?

**Comment by phil-levis** [comment]
> 
> 
> The in-kernel AES driver was removed 3 years ago ([tock/tock#684](https://github.com/tock/tock/pull/684)) and never brought back. At the time the removal was intended to be temporary, but it was never brought back, and I am guessing it would be a decent amount of work to bring it back and test it now. Should we block tock 2.0 on this, or just removed the userspace driver from `libtock-c` (and actually create an issue tracking that we want to bring it back)?

I'd suggest remove. It would be nice to have one, how that it's virtualized, but we should not block Tock 2.0 on this.

**Comment by phil-levis** [comment]
Once all of the other PRs have stabilized, I'll do a cleanup pass of all of the `callback` and `cb` to `upcall`.

**Comment by phil-levis** [comment]
It looks like this is now good. I will do the pass-over to transition command2 -> command, etc. tonight. I will then turn to 2.0 documentation.

**Comment by hudson-ayers** [comment]
Something weird seems to have happened with the merge -- the "files changed" tab appears to include a bunch of the changes already merged into `tock-2.0-dev` by individual PRs.

**Comment by hudson-ayers** [comment]
Oh, nevermind. The confusion is because some of those PRs (removing AES, tmp006) were merged into master after master was last merged into tock-2.0-dev

**Comment by phil-levis** [comment]
@hudson-ayers @bradjc Needs approval.

**Review by hudson-ayers — APPROVED** [review]

**Comment by hudson-ayers** [comment]
I was going to revert the tmp006 commit and cherry-pick the one sent to master, but changes are split between the tmp006 commit and the subsequent merge commit, so we can just deal with the conflict next time master is merged into 2.0-dev

bors r+

**Pull request merged**
