### PR TITLE
bump uncrustify version

### PR DESCRIPTION
**Pull request by ppannuto**
This doesn't look to have any effect on our formatting, but might
hopefully fix M1 mac issues?

@alexandruradovici Does the newest version run on M1 mac?

(uncrustify is also available in homebrew, and the script will pick up your local copy if it's available).

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
I don't have my m1 mac at school, but confirmed that this works fine on Ubuntu 22.04

**Comment by ppannuto** [comment]
Spoke too soon; the format-check cache doesn't check uncrustify version, understandably. There are a handful of small formatting changes, but I don't think the churn is too bad to merit not updating.

**Review by hudson-ayers — APPROVED** [review]

**Review by brghena — APPROVED** [review]

**Comment by alexandruradovici** [comment]
> This doesn't look to have any effect on our formatting, but might hopefully fix M1 mac issues?
> 
> @alexandruradovici Does the newest version run on M1 mac?
>
It seems to work, but when I use `make format` it modifies `buzzer.c` and `ieee802154.c`.
> (uncrustify is also available in homebrew, and the script will pick up your local copy if it's available).

**Comment by ppannuto** [comment]
Additional changes beyond those in fc401d3? That would suggest some non-determinism in the tool, which would be... sad.

Let's land this after the release and then see if there are still issues on a clean tree?

**Review by bradjc — APPROVED** [review]

**Comment by bradjc** [comment]
Can we merge this?

**Pull request merged**
