### PR TITLE
libtock/i2c_master_slave: Add ReadOnly buffer support

### PR DESCRIPTION
**Pull request by alistair23**
This requires https://github.com/tock/tock/pull/2619

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
LGTM once the corresponding Tock PR is merged

**Review by ppannuto — APPROVED** [review]
bors r+

**Comment by ppannuto** [comment]
bors cancel

**Comment by ppannuto** [comment]
bors d+

oops, got jumpy, but agreed this looks good once the kernel is ready for it

**Pull request merged**
