### PR TITLE
HMAC: Initial support for HMAC and HMAC test

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]

**Comment by alistair23** [comment]
This should be ready to merge

**Comment by hudson-ayers** [comment]
I assumed this was blocked on https://github.com/tock/tock/pull/2586 -- does this work with the existing hmac driver?

**Comment by alistair23** [comment]
Yep! There is no change to the HMAC driver so this will work. Although you will hit the double grant enter panic, but the actual interface is working.

**Pull request merged**
