### PR TITLE
Updating ambient_light to 2.0 API.

### PR DESCRIPTION
**Pull request by phil-levis**
Updates the ambient light module to use 2.0 syscalls.

Also removes some whitespace from libtock files that are causing uncrustify to fail.

### CODE REVIEW

**Comment by phil-levis** [comment]
bors try

**Comment by hudson-ayers** [comment]
This PR seems to include a number of unrelated changes to the adc and music apps?

**Comment by phil-levis** [comment]
> 
> 
> This PR seems to include a number of unrelated changes to the adc and music apps?

Ooops, yeah. I accidentally pulled master into it. I'll clean it up now.

**Comment by phil-levis** [comment]
Backing out from merge is too messy, I'll just create a new branch/PR.

**Pull request closed without merging**
