### PR TITLE
Tock 2.0:  Rename command2 to command and subscribe2 to subscribe

### PR DESCRIPTION
**Pull request by hudson-ayers**
```
$ vim
:args **/*.[c,h]
:argdo %s/command2/command/g
:argdo %s/subscribe2/subscribe/g
:wall
```

### CODE REVIEW

**Comment by alevy** [comment]
This just seems to be failing the CI do to formatting (which is likely not a problem with this PR)

**Comment by hudson-ayers** [comment]
ah, shortening command2 --> command requires indendation updates in a couple places.

**Review by ppannuto — APPROVED** [review]
Didn't really review per se, but given the mechanism, lgtm

**Review by alevy — APPROVED** [review]

**Pull request merged**
